# Generated by Django 5.2 on 2026-04-05 14:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_row_level_security'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('SESSION_TRACKING', 'Session & Activity Tracking'), ('ATTENDANCE', 'Attendance'), ('LIVE_CLASSES', 'Live Classes'), ('ASSESSMENTS', 'Assessments & Tests'), ('SECURITY', 'Security'), ('SYSTEM', 'System Health')], max_length=20)),
                ('rule_type', models.CharField(choices=[('FAILED_LOGIN_STREAK', 'Failed Login Streak (X consecutive failures)'), ('SUSPICIOUS_LOGIN', 'Suspicious Login Detected'), ('CONCURRENT_SESSIONS', 'Too Many Concurrent Sessions'), ('INACTIVE_SESSION', 'Session Inactive Too Long'), ('LOW_ATTENDANCE', 'Attendance Below Threshold (%)'), ('ABSENT_STREAK', 'Absent Streak (X consecutive days)'), ('LOW_CLASS_ATTENDANCE', 'Live Class Attendance Below Threshold'), ('CLASS_NOT_STARTED', 'Scheduled Class Not Started'), ('LOW_TEST_SCORE', 'Average Test Score Below Threshold'), ('TEST_NOT_SUBMITTED', 'Test Not Submitted by Deadline'), ('BRUTE_FORCE', 'Brute Force Attack Detected'), ('NEW_DEVICE_LOGIN', 'Login from New/Unknown Device'), ('HIGH_ERROR_RATE', 'High Error Rate Detected'), ('DB_SLOW_QUERIES', 'Slow Database Queries')], max_length=30)),
                ('threshold', models.DecimalField(decimal_places=2, default=0, help_text='Threshold value (e.g., 3 for failures, 75 for percentage)', max_digits=10)),
                ('time_window_minutes', models.IntegerField(default=60, help_text='Time window in minutes to evaluate the rule')),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='WARNING', max_length=10)),
                ('notify_method', models.CharField(choices=[('ADMIN_PANEL', 'Admin Panel Notification'), ('EMAIL', 'Email'), ('BOTH', 'Admin Panel + Email')], default='ADMIN_PANEL', max_length=12)),
                ('notify_emails', models.TextField(blank=True, default='', help_text='Comma-separated email addresses for notifications')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Alert Rule',
                'verbose_name_plural': 'Alert Rules',
                'db_table': 'alert_rules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='WARNING', max_length=10)),
                ('triggered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('acknowledged_by', models.CharField(blank=True, default='', max_length=200)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('is_email_sent', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_logs', to='tenants.tenant')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='alerts.alertrule')),
            ],
            options={
                'verbose_name': 'Alert Log',
                'verbose_name_plural': 'Alert Logs',
                'db_table': 'alert_logs',
                'ordering': ['-triggered_at'],
            },
        ),
    ]
