# Generated by Django 5.2 on 2026-03-31 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auditentry_backuppolicyproxy_backuprecord_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='teacher',
            table='school_teacher',
        ),
    ]
