# Generated by Django 5.2 on 2026-04-05 11:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_student_promotion'),
        ('accounts', '0006_student_promotion'),
        ('tenants', '0002_row_level_security'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchPromotion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_class', models.CharField(choices=[('9', 'Class 9'), ('10', 'Class 10'), ('11', 'Class 11'), ('12', 'Class 12')], max_length=5)),
                ('to_class', models.CharField(choices=[('9', 'Class 9'), ('10', 'Class 10'), ('11', 'Class 11'), ('12', 'Class 12')], max_length=5)),
                ('students_promoted', models.IntegerField(default=0, help_text='Number of students promoted')),
                ('promoted_by', models.UUIDField(blank=True, help_text='Admin user who promoted', null=True)),
                ('promoted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('from_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_promotions_from', to='academics.academicsession')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_promotions', to='tenants.tenant')),
                ('to_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_promotions_to', to='academics.academicsession')),
            ],
            options={
                'verbose_name': 'Batch Promotion',
                'verbose_name_plural': 'Batch Promotions',
                'db_table': 'batch_promotions',
                'ordering': ['-promoted_at'],
            },
        ),
    ]
