# Generated by Django 5.2 on 2026-04-25 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_remove_guardian_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="parent_name",
            field=models.CharField(
                blank=True,
                help_text="Father or guardian's full name.",
                max_length=200,
                null=True,
                verbose_name="Father / Guardian Name",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="parent_phone",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="Father / Guardian Phone",
            ),
        ),
    ]
