# Generated by Django 5.2 on 2026-04-04 21:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_alter_materialaccess_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scholarship',
            options={'ordering': ['stream', 'sort_order', 'name']},
        ),
        migrations.AddField(
            model_name='photogallery',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='icon',
            field=models.CharField(blank=True, help_text='FontAwesome icon class', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='name',
            field=models.CharField(blank=True, default='', help_text='Scholarship name', max_length=500),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='stream',
            field=models.CharField(choices=[('ENGINEERING', 'Engineering'), ('MEDICAL', 'Medical'), ('BOTH', 'Both')], default='ENGINEERING', max_length=20),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='title',
            field=models.CharField(help_text='Legacy field, use name instead', max_length=500),
        ),
    ]
