# Generated by Django 5.2 on 2026-04-04 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_alter_scholarship_options_photogallery_is_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photogallery',
            name='category',
            field=models.CharField(choices=[('Classroom', 'Classroom'), ('Events', 'Events'), ('Achievements', 'Achievements'), ('Campus Life', 'Campus Life'), ('Programs', 'Programs'), ('Infrastructure', 'Infrastructure')], max_length=255),
        ),
    ]
