# Generated by Django 5.2 on 2026-05-14 22:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0016_staffrole_granular_exam_perms"),
        ("tenants", "0002_row_level_security"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIModel",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Provider model id e.g. 'gpt-4o-mini'", max_length=120
                    ),
                ),
                (
                    "display_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "capability",
                    models.CharField(
                        choices=[
                            ("CHAT", "Chat / Completion"),
                            ("EMBEDDING", "Embeddings"),
                            ("STT", "Speech-to-Text"),
                            ("TTS", "Text-to-Speech"),
                            ("VISION", "Vision"),
                            ("IMAGE", "Image generation"),
                            ("RERANK", "Reranker"),
                        ],
                        default="CHAT",
                        max_length=12,
                    ),
                ),
                ("context_window", models.PositiveIntegerField(default=8192)),
                ("max_output_tokens", models.PositiveIntegerField(default=2048)),
                (
                    "input_cost_per_1k",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                (
                    "output_cost_per_1k",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                ("supports_streaming", models.BooleanField(default=True)),
                ("supports_function_calling", models.BooleanField(default=False)),
                ("supports_vision", models.BooleanField(default=False)),
                ("is_enabled", models.BooleanField(db_index=True, default=True)),
                ("is_default_for_capability", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "ai_models",
                "ordering": ("provider__priority", "name"),
            },
        ),
        migrations.CreateModel(
            name="AIFeature",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("DOUBT_SOLVER", "AI Doubt Solver"),
                            ("STUDY_PLANNER", "AI Study Planner"),
                            ("PRACTICE_QUIZ", "Practice Quiz Generator"),
                            ("PERFORMANCE_INSIGHTS", "Performance Insights"),
                            ("LEARNING_PATH", "AI Learning Path"),
                            ("ADAPTIVE_LEARNING", "Adaptive Learning Engine"),
                            ("EXAM_RESULT_PLANNING", "Exam Result Planning"),
                            ("CONTENT_SUMMARISER", "Content Summariser"),
                            ("QUESTION_BANK", "Question Bank AI"),
                            ("TUTOR_CHAT", "AI Tutor Chat"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("name", models.CharField(max_length=180)),
                ("description", models.TextField(blank=True, default="")),
                ("is_enabled", models.BooleanField(db_index=True, default=False)),
                ("is_beta", models.BooleanField(default=False)),
                (
                    "rollout_percent",
                    models.PositiveSmallIntegerField(default=100, help_text="0-100"),
                ),
                ("max_input_tokens", models.PositiveIntegerField(default=4000)),
                ("max_output_tokens", models.PositiveIntegerField(default=1000)),
                (
                    "daily_request_budget",
                    models.PositiveIntegerField(default=0, help_text="0 = unlimited"),
                ),
                ("monthly_token_budget", models.PositiveBigIntegerField(default=0)),
                (
                    "monthly_cost_budget_usd",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("per_user_daily_quota", models.PositiveIntegerField(default=0)),
                ("rate_limit_per_minute", models.PositiveIntegerField(default=60)),
                (
                    "allowed_roles",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of role codes: STUDENT, TEACHER, ADMIN, SUPER_ADMIN.",
                    ),
                ),
                (
                    "input_modes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Subset of ['TEXT','VOICE','IMAGE']",
                    ),
                ),
                (
                    "languages",
                    models.JSONField(
                        blank=True, default=list, help_text="ISO codes e.g. ['en','hi']"
                    ),
                ),
                ("audio_transcription_enabled", models.BooleanField(default=False)),
                ("text_to_speech_enabled", models.BooleanField(default=False)),
                ("conversation_memory_enabled", models.BooleanField(default=True)),
                ("conversation_memory_turns", models.PositiveIntegerField(default=10)),
                (
                    "response_style",
                    models.CharField(
                        choices=[
                            ("BEGINNER", "Beginner"),
                            ("INTERMEDIATE", "Intermediate"),
                            ("ADVANCED", "Advanced"),
                            ("EXAM_FOCUSED", "Exam-focused"),
                        ],
                        default="INTERMEDIATE",
                        max_length=24,
                    ),
                ),
                (
                    "hallucination_guard",
                    models.CharField(
                        choices=[
                            ("OFF", "Off"),
                            ("BASIC", "Basic"),
                            ("STRICT", "Strict"),
                            ("CITATION_REQUIRED", "Citation Required"),
                        ],
                        default="STRICT",
                        max_length=24,
                    ),
                ),
                ("toxicity_filter_enabled", models.BooleanField(default=True)),
                ("prompt_injection_filter_enabled", models.BooleanField(default=True)),
                ("pii_masking_enabled", models.BooleanField(default=True)),
                (
                    "exam_mode_block",
                    models.BooleanField(
                        default=True,
                        help_text="Block this feature while student is in an exam.",
                    ),
                ),
                ("teacher_escalation_enabled", models.BooleanField(default=True)),
                ("config", models.JSONField(blank=True, default=dict)),
                ("last_health_at", models.DateTimeField(blank=True, null=True)),
                ("last_health_ok", models.BooleanField(default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="NULL = platform-global default. Tenant rows override globals.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "default_model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="features",
                        to="ai_core.aimodel",
                    ),
                ),
                (
                    "fallback_models",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Ordered failover candidates.",
                        related_name="fallback_for_features",
                        to="ai_core.aimodel",
                    ),
                ),
            ],
            options={
                "db_table": "ai_features",
                "ordering": ("tenant_id", "code"),
            },
        ),
        migrations.CreateModel(
            name="AIPrompt",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.SlugField(max_length=160)),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                (
                    "feature",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional — leave NULL for shared / utility prompts.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prompts",
                        to="ai_core.aifeature",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="NULL = platform-global default. Tenant rows override globals.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "ai_prompts",
                "ordering": ("name",),
                "unique_together": {("tenant", "name")},
            },
        ),
        migrations.CreateModel(
            name="AIPromptVersion",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("UNDER_REVIEW", "Under review"),
                            ("APPROVED", "Approved"),
                            ("PUBLISHED", "Published"),
                            ("ROLLED_BACK", "Rolled back"),
                            ("DEPRECATED", "Deprecated"),
                        ],
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                ("system_prompt", models.TextField(blank=True, default="")),
                (
                    "user_template",
                    models.TextField(
                        blank=True, default="", help_text="Jinja-style placeholders."
                    ),
                ),
                (
                    "variables",
                    models.JSONField(
                        blank=True, default=list, help_text="Declared variable names."
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Per-version overrides: temperature, top_p, max_tokens, etc.",
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("rolled_back_at", models.DateTimeField(blank=True, null=True)),
                ("change_note", models.TextField(blank=True, default="")),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_prompt_versions_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_prompt_versions_authored",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "prompt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="ai_core.aiprompt",
                    ),
                ),
            ],
            options={
                "db_table": "ai_prompt_versions",
                "ordering": ("prompt", "-version"),
            },
        ),
        migrations.CreateModel(
            name="AILearningPath",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("STUDY_PLAN", "Study plan"),
                            ("LEARNING_PATH", "Learning path"),
                            ("ADAPTIVE", "Adaptive sequence"),
                            ("EXAM_PLAN", "Exam result plan"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="DRAFT",
                        max_length=12,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("summary", models.TextField(blank=True, default="")),
                (
                    "target_exam_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("target_date", models.DateField(blank=True, null=True)),
                ("plan", models.JSONField(blank=True, default=dict)),
                ("completion_percent", models.FloatField(default=0)),
                ("adherence_percent", models.FloatField(default=0)),
                ("planned_minutes", models.PositiveIntegerField(default=0)),
                ("actual_minutes", models.PositiveIntegerField(default=0)),
                ("confidence", models.FloatField(blank=True, null=True)),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_learning_paths",
                        to="accounts.student",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="NULL = platform-global default. Tenant rows override globals.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "generated_by_model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="learning_paths",
                        to="ai_core.aimodel",
                    ),
                ),
                (
                    "generated_by_prompt_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="learning_paths",
                        to="ai_core.aipromptversion",
                    ),
                ),
            ],
            options={
                "db_table": "ai_learning_paths",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddField(
            model_name="aifeature",
            name="active_prompt_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="active_for",
                to="ai_core.aipromptversion",
            ),
        ),
        migrations.CreateModel(
            name="AIProvider",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("OPENAI", "OpenAI"),
                            ("ANTHROPIC", "Anthropic"),
                            ("AZURE_OPENAI", "Azure OpenAI"),
                            ("GOOGLE", "Google Gemini"),
                            ("LOCAL", "Local / Self-hosted"),
                            ("HUGGINGFACE", "HuggingFace"),
                            ("OPENROUTER", "OpenRouter"),
                            ("AWS_BEDROCK", "AWS Bedrock"),
                            ("WHISPER", "Whisper (STT)"),
                            ("AZURE_SPEECH", "Azure Speech"),
                        ],
                        max_length=24,
                    ),
                ),
                ("base_url", models.URLField(blank=True, default="")),
                (
                    "api_key_encrypted",
                    models.TextField(
                        blank=True, default="", help_text="Fernet-encrypted"
                    ),
                ),
                ("extra_headers", models.JSONField(blank=True, default=dict)),
                ("timeout_seconds", models.PositiveIntegerField(default=30)),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=100, help_text="Lower wins in failover ordering."
                    ),
                ),
                (
                    "weight",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Used by weighted routing within same priority.",
                    ),
                ),
                ("is_enabled", models.BooleanField(db_index=True, default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("DEGRADED", "Degraded"),
                            ("OUTAGE", "Outage"),
                            ("DISABLED", "Disabled"),
                        ],
                        default="ACTIVE",
                        max_length=12,
                    ),
                ),
                ("consecutive_failures", models.PositiveIntegerField(default=0)),
                ("last_failure_at", models.DateTimeField(blank=True, null=True)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("circuit_open_until", models.DateTimeField(blank=True, null=True)),
                ("avg_latency_ms", models.FloatField(default=0.0)),
                (
                    "success_rate",
                    models.FloatField(default=1.0, help_text="0..1 rolling window"),
                ),
                ("notes", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "ai_providers",
                "ordering": ("priority", "name"),
                "indexes": [
                    models.Index(
                        fields=["is_enabled", "status"],
                        name="ai_provider_is_enab_1103b8_idx",
                    ),
                    models.Index(
                        fields=["kind", "is_enabled"],
                        name="ai_provider_kind_54c393_idx",
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="aimodel",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="models",
                to="ai_core.aiprovider",
            ),
        ),
        migrations.CreateModel(
            name="AICostTracking",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("requests", models.PositiveBigIntegerField(default=0)),
                ("failed_requests", models.PositiveBigIntegerField(default=0)),
                ("input_tokens", models.PositiveBigIntegerField(default=0)),
                ("output_tokens", models.PositiveBigIntegerField(default=0)),
                ("total_tokens", models.PositiveBigIntegerField(default=0)),
                (
                    "cost_usd",
                    models.DecimalField(decimal_places=6, default=0, max_digits=14),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="NULL = platform-global default. Tenant rows override globals.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "feature",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cost_rows",
                        to="ai_core.aifeature",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ai_core.aimodel",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ai_core.aiprovider",
                    ),
                ),
            ],
            options={
                "db_table": "ai_cost_tracking",
                "ordering": ("-date",),
            },
        ),
        migrations.CreateModel(
            name="AIStudentProfile",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "mastery_map",
                    models.JSONField(
                        blank=True, default=dict, help_text="topic_id -> mastery 0..1"
                    ),
                ),
                ("weak_topics", models.JSONField(blank=True, default=list)),
                ("strong_topics", models.JSONField(blank=True, default=list)),
                (
                    "learning_style",
                    models.CharField(blank=True, default="", max_length=24),
                ),
                (
                    "preferred_language",
                    models.CharField(blank=True, default="en", max_length=8),
                ),
                ("avg_session_minutes", models.FloatField(default=0)),
                ("last_active_at", models.DateTimeField(blank=True, null=True)),
                ("engagement_score", models.FloatField(default=0)),
                ("consistency_score", models.FloatField(default=0)),
                ("predicted_score", models.FloatField(blank=True, null=True)),
                ("prediction_confidence", models.FloatField(blank=True, null=True)),
                (
                    "risk_band",
                    models.CharField(
                        choices=[
                            ("TOP", "Top performer"),
                            ("SAFE", "Safe zone"),
                            ("MEDIUM", "Medium risk"),
                            ("HIGH", "High risk"),
                        ],
                        db_index=True,
                        default="SAFE",
                        max_length=8,
                    ),
                ),
                (
                    "embedding_ref",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("embedding_updated_at", models.DateTimeField(blank=True, null=True)),
                ("config", models.JSONField(blank=True, default=dict)),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_profile",
                        to="accounts.student",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="NULL = platform-global default. Tenant rows override globals.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "ai_student_profiles",
            },
        ),
        migrations.CreateModel(
            name="AIUsageLog",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "request_id",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                (
                    "correlation_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                ("user_role", models.CharField(blank=True, default="", max_length=32)),
                (
                    "actor_type",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="STUDENT/TEACHER/ADMIN/SYSTEM",
                        max_length=24,
                    ),
                ),
                ("actor_id", models.CharField(blank=True, default="", max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                            ("TIMEOUT", "Timeout"),
                            ("BLOCKED", "Blocked by policy"),
                            ("RATE_LIMITED", "Rate limited"),
                            ("FALLBACK", "Served by fallback"),
                        ],
                        default="SUCCESS",
                        max_length=16,
                    ),
                ),
                ("error_code", models.CharField(blank=True, default="", max_length=64)),
                ("error_message", models.TextField(blank=True, default="")),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                ("total_tokens", models.PositiveIntegerField(default=0)),
                (
                    "cost_usd",
                    models.DecimalField(decimal_places=6, default=0, max_digits=12),
                ),
                ("latency_ms", models.PositiveIntegerField(default=0)),
                ("confidence_score", models.FloatField(blank=True, null=True)),
                ("abuse_score", models.FloatField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "feature",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usage",
                        to="ai_core.aifeature",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usage",
                        to="ai_core.aimodel",
                    ),
                ),
                (
                    "prompt_version",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usage",
                        to="ai_core.aipromptversion",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usage",
                        to="ai_core.aiprovider",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="NULL = platform-global default. Tenant rows override globals.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_usage",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ai_usage_logs",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="AIFeedback",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "verdict",
                    models.CharField(
                        choices=[
                            ("UP", "Thumbs up"),
                            ("DOWN", "Thumbs down"),
                            ("NEUTRAL", "Neutral"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="1..5", null=True
                    ),
                ),
                ("comment", models.TextField(blank=True, default="")),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="NULL = platform-global default. Tenant rows override globals.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_feedback",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="ai_core.aiusagelog",
                    ),
                ),
            ],
            options={
                "db_table": "ai_feedback",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="AIAuditLog",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("feature_code", models.CharField(db_index=True, max_length=32)),
                (
                    "model_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "provider_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("prompt_text", models.TextField(blank=True, default="")),
                ("response_text", models.TextField(blank=True, default="")),
                ("redacted_prompt", models.TextField(blank=True, default="")),
                ("redacted_response", models.TextField(blank=True, default="")),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user_agent",
                    models.CharField(blank=True, default="", max_length=400),
                ),
                ("flagged", models.BooleanField(db_index=True, default=False)),
                (
                    "flag_reason",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="NULL = platform-global default. Tenant rows override globals.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_audit",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usage",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit",
                        to="ai_core.aiusagelog",
                    ),
                ),
            ],
            options={
                "db_table": "ai_audit_logs",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="aipromptversion",
            index=models.Index(
                fields=["prompt", "status"], name="ai_prompt_v_prompt__dea495_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="aipromptversion",
            unique_together={("prompt", "version")},
        ),
        migrations.AddIndex(
            model_name="ailearningpath",
            index=models.Index(
                fields=["tenant", "kind", "status"],
                name="ai_learning_tenant__5bd7f2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ailearningpath",
            index=models.Index(
                fields=["student", "kind"], name="ai_learning_student_4c9cc5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aifeature",
            index=models.Index(
                fields=["is_enabled", "code"], name="ai_features_is_enab_f08baa_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="aifeature",
            unique_together={("tenant", "code")},
        ),
        migrations.AddIndex(
            model_name="aimodel",
            index=models.Index(
                fields=["capability", "is_enabled"], name="ai_models_capabil_632494_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aimodel",
            index=models.Index(
                fields=["is_default_for_capability"],
                name="ai_models_is_defa_31d943_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="aimodel",
            unique_together={("provider", "name")},
        ),
        migrations.AddIndex(
            model_name="aicosttracking",
            index=models.Index(
                fields=["tenant", "date"], name="ai_cost_tra_tenant__9f2f97_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aicosttracking",
            index=models.Index(
                fields=["date", "feature"], name="ai_cost_tra_date_afae0f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="aicosttracking",
            unique_together={("tenant", "date", "feature", "model")},
        ),
        migrations.AddIndex(
            model_name="aistudentprofile",
            index=models.Index(
                fields=["tenant", "risk_band"], name="ai_student__tenant__961c06_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aiusagelog",
            index=models.Index(
                fields=["tenant", "created_at"], name="ai_usage_lo_tenant__090dd9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aiusagelog",
            index=models.Index(
                fields=["feature", "created_at"], name="ai_usage_lo_feature_94fb32_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aiusagelog",
            index=models.Index(
                fields=["provider", "created_at"], name="ai_usage_lo_provide_84f38f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aiusagelog",
            index=models.Index(
                fields=["status", "created_at"], name="ai_usage_lo_status_501e3b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aifeedback",
            index=models.Index(fields=["usage"], name="ai_feedback_usage_i_7e9b8d_idx"),
        ),
        migrations.AddIndex(
            model_name="aifeedback",
            index=models.Index(
                fields=["verdict", "created_at"], name="ai_feedback_verdict_285e58_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aiauditlog",
            index=models.Index(
                fields=["tenant", "created_at"], name="ai_audit_lo_tenant__15b7e9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aiauditlog",
            index=models.Index(
                fields=["feature_code", "created_at"],
                name="ai_audit_lo_feature_4e958b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aiauditlog",
            index=models.Index(
                fields=["flagged", "created_at"], name="ai_audit_lo_flagged_99a046_idx"
            ),
        ),
    ]
