# Generated by Django 5.2 on 2026-03-31 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_batch_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batchstudent',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterModelOptions(
            name='batchteacher',
            options={'verbose_name': 'Teacher', 'verbose_name_plural': 'Teachers'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['name'], 'verbose_name': 'Group', 'verbose_name_plural': 'Groups'},
        ),
        migrations.AlterModelOptions(
            name='subjectsection',
            options={'ordering': ['name'], 'verbose_name': 'Subject Section', 'verbose_name_plural': 'Subject Sections'},
        ),
    ]
