# Generated by Django 5.2 on 2026-03-31 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_drop_eduassist_tables'),
        ('accounts', '0005_alter_teacher_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicsession',
            options={'ordering': ['-start_date'], 'verbose_name': 'Academic Session', 'verbose_name_plural': 'Academic Sessions'},
        ),
        # Handle M2M through→simple conversion via SeparateDatabaseAndState:
        # DB side: drop old batch_teachers through-table, create auto M2M table
        # State side: alter the field definition
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='batch',
                    name='teachers',
                    field=models.ManyToManyField(blank=True, related_name='teaching_batches', to='accounts.teacher'),
                ),
                migrations.DeleteModel(
                    name='BatchTeacher',
                ),
            ],
            database_operations=[
                # Drop old through-table
                migrations.RunSQL(
                    sql='DROP TABLE IF EXISTS "batch_teachers" CASCADE;',
                    reverse_sql=migrations.RunSQL.noop,
                ),
                # Create auto M2M table
                migrations.RunSQL(
                    sql='''
                        CREATE TABLE IF NOT EXISTS "batches_teachers" (
                            "id" bigserial NOT NULL PRIMARY KEY,
                            "batch_id" uuid NOT NULL REFERENCES "batches" ("id") DEFERRABLE INITIALLY DEFERRED,
                            "teacher_id" uuid NOT NULL REFERENCES "school_teacher" ("id") DEFERRABLE INITIALLY DEFERRED,
                            UNIQUE ("batch_id", "teacher_id")
                        );
                    ''',
                    reverse_sql='DROP TABLE IF EXISTS "batches_teachers";',
                ),
            ],
        ),
        migrations.AlterModelTable(
            name='academicsession',
            table='session',
        ),
        # Drop the old 'users' table (SQL Server import, empty, incompatible schema)
        # before renaming batch_students → users
        migrations.RunSQL(
            sql='DROP TABLE IF EXISTS "users" CASCADE;',
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterModelTable(
            name='batchstudent',
            table='users',
        ),
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.AlterModelTable(
            name='chapter',
            table='chapter',
        ),
        migrations.AlterModelTable(
            name='city',
            table='city',
        ),
        migrations.AlterModelTable(
            name='school',
            table='school',
        ),
        migrations.AlterModelTable(
            name='state',
            table='state',
        ),
        migrations.AlterModelTable(
            name='subject',
            table='subject',
        ),
    ]
