# Generated by Django 5.2 on 2026-03-31 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0008_users_add_legacy_columns_remove_student_fk"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveConstraint(
                    model_name="users",
                    name="uq_batch_student",
                ),
            ],
            database_operations=[
                # Constraint doesn't exist in DB (was on old batch_students table)
            ],
        ),
    ]
