# Generated by Django 5.2 on 2026-04-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_remove_users_uq_batch_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='city_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='District Name'),
        ),
        migrations.AlterField(
            model_name='users',
            name='city_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='City/Village'),
        ),
        migrations.AlterField(
            model_name='users',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='users',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Father/Guardian Name'),
        ),
        migrations.AlterField(
            model_name='users',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='handicapped',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone (User/Password)'),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone1',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Father Phone'),
        ),
        migrations.AlterField(
            model_name='users',
            name='previous_class_marks',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Previous Year Total Marks'),
        ),
        migrations.AlterField(
            model_name='users',
            name='school_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='School'),
        ),
        migrations.AlterField(
            model_name='users',
            name='state_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='State'),
        ),
    ]
