# Generated by Django 5.2 on 2026-04-04 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_update_users_field_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phone1',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Father/Guardian Phone'),
        ),
    ]
