# Generated by Django 5.2 on 2026-05-01 21:12

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


def seed_flags_and_settings(apps, schema_editor):
    try:
        from assessments.permissions import (
            ensure_exam_feature_flags, ensure_exam_settings,
        )
        ensure_exam_feature_flags()
        ensure_exam_settings()
    except Exception:
        pass


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0003_seed_exam_feature_flags"),
        ("tenants", "0002_row_level_security"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version_number", models.IntegerField()),
                ("label", models.CharField(blank=True, default="", max_length=200)),
                (
                    "snapshot",
                    models.JSONField(
                        help_text="Full Test+Sections+Questions JSON snapshot."
                    ),
                ),
                (
                    "summary",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Quick stats: question_count, total_marks, etc.",
                    ),
                ),
                ("created_by_id", models.UUIDField(blank=True, null=True)),
                (
                    "created_by_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("note", models.TextField(blank=True, default="")),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tenants.tenant"
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="assessments.test",
                    ),
                ),
            ],
            options={
                "db_table": "test_versions",
                "ordering": ["-version_number"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "test"], name="idx_test_version_test"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("test", "version_number"), name="uq_test_version"
                    )
                ],
            },
        ),
        migrations.RunPython(seed_flags_and_settings, noop),
    ]
