# Generated by Django 5.2 on 2026-05-03 13:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0005_offlinemarks_test_batch"),
        ("tenants", "0002_row_level_security"),
    ]

    operations = [
        migrations.CreateModel(
            name="ZipImportLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("file_size_bytes", models.BigIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                            ("REJECTED", "Rejected (validation)"),
                        ],
                        db_index=True,
                        default="SUCCESS",
                        max_length=12,
                    ),
                ),
                ("rows_total", models.IntegerField(default=0)),
                ("rows_created", models.IntegerField(default=0)),
                ("rows_updated", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("uploaded_by", models.UUIDField(blank=True, null=True)),
                (
                    "uploaded_by_label",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zip_import_logs",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="zip_import_logs",
                        to="assessments.test",
                    ),
                ),
            ],
            options={
                "verbose_name": "ZIP import log",
                "verbose_name_plural": "ZIP import history",
                "db_table": "zip_import_logs",
                "ordering": ["-uploaded_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "-uploaded_at"],
                        name="idx_zip_log_tenant_time",
                    )
                ],
            },
        ),
    ]
