# Generated by Django 5.2 on 2026-04-05 20:06

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_batchpromotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchPromotionProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Batch Promotion',
                'verbose_name_plural': 'Batch Promotions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.batchpromotion',),
        ),
        migrations.CreateModel(
            name='StudentPromotionProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Student Promotion',
                'verbose_name_plural': 'Student Promotions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.studentpromotion',),
        ),
    ]
