# Generated by Django 5.2 on 2026-04-05 14:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_tracking', '0002_alter_loginhistory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdevice',
            name='last_seen',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='last_activity_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
