"""Deterministic mock client used in dev / CI / when an API key is missing.

Returns a synthesized response that includes echoes of the user message so
tests can assert on it, plus realistic token counts based on word length.
"""
from __future__ import annotations

import hashlib
import random

from .base import BaseClient, RawCompletion


def _approx_tokens(text: str) -> int:
    # Rough heuristic: ~0.75 tokens per word
    if not text:
        return 0
    return max(1, int(len(text.split()) / 0.75))


class MockClient(BaseClient):
    """Fake completions; useful for unit tests + offline development."""

    name = "mock"

    def chat(self, *, model_name: str, system: str, user: str, **opts) -> RawCompletion:
        # Deterministic seed so the same prompt yields the same canned text.
        h = hashlib.sha1((system + "|" + user).encode("utf-8")).hexdigest()
        seed = int(h[:8], 16)
        rng = random.Random(seed)
        snippet = user.strip().splitlines()[-1][:120] if user else "Hello"
        canned = [
            "Here is a clear, step-by-step explanation:",
            "Let's break this down into smaller parts:",
            "Great question — here's how I'd think about it:",
            "Based on the provided context, the answer is:",
        ]
        prefix = rng.choice(canned)
        reply = (
            f"{prefix}\n\n"
            f"1. You asked about: \"{snippet}\".\n"
            f"2. Key idea: this is a mock LLM response generated by the gateway because "
            f"no upstream provider key was configured.\n"
            f"3. In production, this response will come from `{self.provider.name}/{model_name}`.\n"
        )
        return RawCompletion(
            text=reply,
            input_tokens=_approx_tokens(system) + _approx_tokens(user),
            output_tokens=_approx_tokens(reply),
            raw={"mock": True, "seed": seed, "model": model_name},
        )

    def embed(self, *, model_name: str, texts: list[str], **opts) -> RawCompletion:
        # Stable pseudo-embedding (8 dims) derived from sha1 of joined text.
        joined = "\n".join(texts or [])
        h = hashlib.sha1(joined.encode("utf-8")).digest()
        emb = [(b - 128) / 128.0 for b in h[:8]]
        return RawCompletion(
            embedding=emb,
            input_tokens=_approx_tokens(joined),
            output_tokens=0,
            raw={"mock": True, "dims": len(emb)},
        )

    def transcribe(self, *, model_name: str, audio_bytes: bytes, **opts) -> RawCompletion:
        text = f"[mock transcription of {len(audio_bytes)} bytes]"
        return RawCompletion(text=text, input_tokens=0, output_tokens=_approx_tokens(text))

    def tts(self, *, model_name: str, text: str, **opts) -> bytes:
        return b"MOCK-WAV:" + text.encode("utf-8")[:256]
