# Generated by Django 5.2 on 2026-03-25 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0002_alter_scheduledclass_options"),
        ("system_config", "0006_alter_reporttemplate_filters_json_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassLinkConfigProxy",
            fields=[],
            options={
                "verbose_name": "Class Link Configuration",
                "verbose_name_plural": "Class Link Configurations",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("system_config.classlinkconfig",),
        ),
        migrations.CreateModel(
            name="IntegrationConfigProxy",
            fields=[],
            options={
                "verbose_name": "Integration config",
                "verbose_name_plural": "Integration configs",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("system_config.integrationconfig",),
        ),
    ]
