# Generated by Django 5.2 on 2026-03-29 15:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_batch_options_alter_category_options_and_more'),
        ('accounts', '0004_auditentry_backuppolicyproxy_backuprecord_and_more'),
        ('classes', '0003_classlinkconfigproxy_integrationconfigproxy'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='integrationconfigproxy',
            options={'verbose_name': 'YouTube integration config', 'verbose_name_plural': 'YouTube integration configs'},
        ),
        migrations.AddField(
            model_name='scheduledclass',
            name='is_recurring_instance',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='RecurringClassTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='e.g. Physics Daily – Batch A', max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('class_code_prefix', models.CharField(help_text='Auto-generated class codes will be <PREFIX>-YYYYMMDD. e.g. PHY-A', max_length=30)),
                ('recurrence_type', models.CharField(choices=[('DAILY', 'Every Day'), ('WEEKDAYS', 'Weekdays Only (Mon–Fri)'), ('WEEKLY', 'Specific Days of Week')], default='DAILY', max_length=10)),
                ('recurrence_days', models.JSONField(blank=True, default=list, help_text="For 'Specific Days': list of weekday numbers [0=Mon … 6=Sun]")),
                ('start_time', models.TimeField(help_text='Class start time (uses class_timezone)')),
                ('end_time', models.TimeField(help_text='Class end time')),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('class_timezone', models.CharField(default='Asia/Kolkata', max_length=50)),
                ('effective_from', models.DateField(help_text='Start generating classes from this date')),
                ('effective_until', models.DateField(blank=True, help_text='Stop generating after this date. Leave blank to run indefinitely.', null=True)),
                ('subject', models.CharField(blank=True, choices=[('PHYSICS', 'Physics'), ('CHEMISTRY', 'Chemistry'), ('MATHEMATICS', 'Mathematics'), ('BIOLOGY', 'Biology')], max_length=20, null=True)),
                ('privacy_status', models.CharField(choices=[('PRIVATE', 'Private'), ('UNLISTED', 'Unlisted')], default='UNLISTED', max_length=10)),
                ('auto_create_broadcast', models.BooleanField(default=True, help_text='Automatically create a YouTube Live broadcast for each generated class')),
                ('advance_create_hours', models.IntegerField(default=1, help_text='Create the YouTube broadcast this many hours before class start time')),
                ('access_type', models.CharField(choices=[('BATCH_ONLY', 'Batch Only'), ('MULTI_BATCH', 'Multi-Batch'), ('ALL_STUDENTS', 'All Students'), ('CUSTOM', 'Custom')], default='BATCH_ONLY', max_length=15)),
                ('allowed_batches', models.JSONField(blank=True, default=list)),
                ('allowed_students', models.JSONField(blank=True, default=list)),
                ('attendance_mode', models.CharField(choices=[('AUTO', 'Automatic'), ('MANUAL', 'Manual'), ('HYBRID', 'Hybrid')], default='AUTO', max_length=10)),
                ('auto_attendance_threshold_minutes', models.IntegerField(default=15)),
                ('min_watch_percent_for_present', models.IntegerField(default=70)),
                ('is_active', models.BooleanField(default=True)),
                ('last_generated_date', models.DateField(blank=True, help_text='Most recent date a class was auto-generated for this template', null=True)),
                ('total_classes_generated', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_templates', to='academics.batch')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_templates', to='accounts.teacher')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_templates', to='tenants.tenant')),
                ('youtube_channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.youtubechannel')),
            ],
            options={
                'db_table': 'recurring_class_templates',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='scheduledclass',
            name='recurring_template',
            field=models.ForeignKey(blank=True, help_text='Set automatically when this class was generated from a recurring template', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_classes', to='classes.recurringclasstemplate'),
        ),
        migrations.AddIndex(
            model_name='recurringclasstemplate',
            index=models.Index(fields=['tenant', 'is_active'], name='idx_rct_tenant_active'),
        ),
        migrations.AddIndex(
            model_name='recurringclasstemplate',
            index=models.Index(fields=['tenant', 'teacher'], name='idx_rct_tenant_teacher'),
        ),
    ]
