# Generated by Django 5.2 on 2026-03-29 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0004_add_recurring_class_template"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="classaccesstoken",
            options={
                "verbose_name": "Class Access Token",
                "verbose_name_plural": "Class Access Tokens",
            },
        ),
        migrations.AlterModelOptions(
            name="classlinkconfigproxy",
            options={
                "verbose_name": "Streaming Platform",
                "verbose_name_plural": "Streaming Platforms",
            },
        ),
        migrations.AlterModelOptions(
            name="classwatchtime",
            options={
                "verbose_name": "Class Watch Time",
                "verbose_name_plural": "Class Watch Times",
            },
        ),
        migrations.AlterModelOptions(
            name="integrationconfigproxy",
            options={
                "verbose_name": "YouTube Integration Config",
                "verbose_name_plural": "YouTube Integration Configs",
            },
        ),
        migrations.AlterModelOptions(
            name="scheduledclass",
            options={
                "ordering": ["-scheduled_date", "-start_time"],
                "verbose_name": "Live Class",
                "verbose_name_plural": "Live Classes",
            },
        ),
        migrations.AlterModelOptions(
            name="youtubechannel",
            options={
                "verbose_name": "YouTube Channel",
                "verbose_name_plural": "YouTube Channels",
            },
        ),
        migrations.AddField(
            model_name="scheduledclass",
            name="teacher_join_notified",
            field=models.BooleanField(
                default=False,
                help_text="Whether a notification was sent confirming the teacher has joined",
            ),
        ),
        migrations.AddField(
            model_name="scheduledclass",
            name="teacher_joined_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the teacher actually joined/started the class",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="scheduledclass",
            name="reschedule_count",
            field=models.IntegerField(
                default=0,
                help_text="Number of times this class has been rescheduled. Incremented automatically when a class is moved to a new date/time.",
            ),
        ),
    ]
