# Generated by Django 5.2 on 2026-03-28 18:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0003_alter_batch_options_alter_category_options_and_more'),
        ('accounts', '0004_auditentry_backuppolicyproxy_backuprecord_and_more'),
        ('classes', '0006_alter_scheduledclass_status'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Name of the class schedule', max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('rrule', models.TextField(help_text='iCalendar RRULE string, e.g. FREQ=WEEKLY;BYDAY=MO,WE,FR')),
                ('start_time', models.TimeField(help_text='Class start time each day (local)')),
                ('duration_mins', models.IntegerField(default=60, help_text='Duration of each session in minutes')),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=50)),
                ('start_date', models.DateField(help_text='When the schedule begins')),
                ('end_date', models.DateField(blank=True, help_text='When the schedule ends (blank = runs forever)', null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('SUPERSEDED', 'Superseded'), ('ENDED', 'Ended')], default='DRAFT', max_length=15)),
                ('generated_until', models.DateField(blank=True, help_text='How far ahead sessions have been created (internal)', null=True)),
                ('effective_from', models.DateField(blank=True, help_text='Date from which the new rule takes effect (must be >= tomorrow)', null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_data', models.JSONField(blank=True, default=dict)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_rules', to='academics.batch')),
                ('parent_rule', models.ForeignKey(blank=True, help_text="If duplicated from another rule, the original's ID", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_rules', to='scheduling.recurringrule')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_rules', to='academics.subject')),
                ('superseded_by', models.ForeignKey(blank=True, help_text='ID of the new rule that replaced this one', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='scheduling.recurringrule')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_rules', to='accounts.teacher')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_rules', to='tenants.tenant')),
                ('youtube_channel', models.ForeignKey(blank=True, help_text='Default YouTube channel for all sessions generated from this rule', null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.youtubechannel')),
            ],
            options={
                'db_table': 'recurring_rules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('MANUAL', 'Manual'), ('CLASS_GROUP', 'Class Group'), ('CSV_UPLOAD', 'CSV Upload'), ('AUTO_MIGRATION', 'Auto Migration (Schedule Update)')], default='MANUAL', max_length=20)),
                ('enrolled_by', models.UUIDField(blank=True, help_text='Admin who enrolled', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('enrolled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('unenrolled_at', models.DateTimeField(blank=True, null=True)),
                ('class_group', models.ForeignKey(blank=True, help_text='If enrolled via class group', null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.batch')),
                ('class_instance', models.ForeignKey(blank=True, help_text='For ad-hoc / one-off classes', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='classes.scheduledclass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='accounts.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='tenants.tenant')),
                ('recurring_rule', models.ForeignKey(blank=True, help_text='For recurring classes', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='scheduling.recurringrule')),
            ],
            options={
                'db_table': 'enrollments',
            },
        ),
        migrations.CreateModel(
            name='BlackoutDate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('reason', models.CharField(help_text="e.g. 'Diwali Holiday'", max_length=500)),
                ('applies_to_batches', models.JSONField(blank=True, default=list, help_text='List of batch UUIDs; empty = applies to all')),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blackout_dates', to='tenants.tenant')),
            ],
            options={
                'db_table': 'blackout_dates',
                'ordering': ['date'],
                'indexes': [models.Index(fields=['tenant', 'date'], name='idx_blackout_date')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'date'), name='uq_blackout_date_per_tenant')],
            },
        ),
        migrations.CreateModel(
            name='ClassAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late')], default='ABSENT', max_length=10)),
                ('marked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('class_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_attendance', to='classes.scheduledclass')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_class_attendance', to='accounts.teacher')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_attendance', to='accounts.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_attendance_records', to='tenants.tenant')),
            ],
            options={
                'db_table': 'class_attendance',
                'indexes': [models.Index(fields=['tenant', 'class_instance', 'status'], name='idx_class_att_status')],
                'constraints': [models.UniqueConstraint(fields=('class_instance', 'student'), name='uq_class_attendance_per_student')],
            },
        ),
        migrations.AddIndex(
            model_name='recurringrule',
            index=models.Index(fields=['tenant', 'status'], name='idx_rr_status'),
        ),
        migrations.AddIndex(
            model_name='recurringrule',
            index=models.Index(fields=['tenant', 'teacher'], name='idx_rr_teacher'),
        ),
        migrations.AddIndex(
            model_name='recurringrule',
            index=models.Index(fields=['tenant', 'subject'], name='idx_rr_subject'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['tenant', 'student'], name='idx_enroll_student'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['tenant', 'recurring_rule'], name='idx_enroll_rule'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['tenant', 'class_instance'], name='idx_enroll_class'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('recurring_rule__isnull', False)), fields=('student', 'recurring_rule'), name='uq_enrollment_recurring'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('class_instance__isnull', False), ('is_active', True)), fields=('student', 'class_instance'), name='uq_enrollment_adhoc'),
        ),
    ]
