#!/usr/bin/env bash
# =============================================================================
# pg18-rocky8-setup.sh — Install & Configure PostgreSQL 18 on Rocky Linux 8
#
# Run this script ONCE on the TARGET machine as root BEFORE migrating data.
#
# Usage:
#   export DB_PASSWORD='<strong-password>'
#   export APP_SERVER_IP='192.168.1.113'   # Allow connections from this IP
#   bash pg18-rocky8-setup.sh
#
# What it does:
#   1. Installs PostgreSQL 18 from the official PGDG repo
#   2. Initialises the cluster
#   3. Tunes postgresql.conf for production
#   4. Creates the LMS database role and database
#   5. Configures pg_hba.conf to accept connections from the app server
#   6. Opens firewalld port 5432
# =============================================================================
set -euo pipefail

# ── Variables (override via env) ─────────────────────────────────────────────
DB_NAME="${DB_NAME:-LMS_PROD_DB}"
DB_USER="${DB_USER:-lms_app_user}"
DB_PASSWORD="${DB_PASSWORD:?ERROR: Set DB_PASSWORD before running this script}"
APP_SERVER_IP="${APP_SERVER_IP:?ERROR: Set APP_SERVER_IP (the Docker host that connects to PG)}"

PG_MAJOR=18
PGDATA="/var/lib/pgsql/${PG_MAJOR}/data"
PG_BIN="/usr/pgsql-${PG_MAJOR}/bin"
PG_SVC="postgresql-${PG_MAJOR}"

RED='\033[0;31m'; GREEN='\033[0;32m'; CYAN='\033[0;36m'; YELLOW='\033[1;33m'; NC='\033[0m'
info()  { echo -e "${CYAN}[$(date '+%H:%M:%S')] INFO  ${NC} $*"; }
ok()    { echo -e "${GREEN}[$(date '+%H:%M:%S')] OK    ${NC} $*"; }
warn()  { echo -e "${YELLOW}[$(date '+%H:%M:%S')] WARN  ${NC} $*"; }
die()   { echo -e "${RED}[$(date '+%H:%M:%S')] ERROR ${NC} $*" >&2; exit 1; }

[[ $EUID -ne 0 ]] && die "Must be run as root"

# ── 1. Install PGDG repo for EL8 ─────────────────────────────────────────────
info "Installing PGDG repository for EL8..."
dnf install -y https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm || true

# Disable the built-in AppStream postgresql module (conflicts with PGDG)
info "Disabling AppStream postgresql module..."
dnf module disable -y postgresql

# ── 2. Install PostgreSQL 18 ─────────────────────────────────────────────────
info "Installing postgresql${PG_MAJOR}-server and postgresql${PG_MAJOR}-contrib..."
dnf install -y \
    "postgresql${PG_MAJOR}-server" \
    "postgresql${PG_MAJOR}-contrib" \
    "postgresql${PG_MAJOR}"

ok "PostgreSQL ${PG_MAJOR} installed: $($PG_BIN/postgres --version)"

# ── 3. Initialise the cluster ─────────────────────────────────────────────────
if [[ ! -f "${PGDATA}/PG_VERSION" ]]; then
    info "Initialising database cluster at ${PGDATA}..."
    "${PG_BIN}/postgresql-${PG_MAJOR}-setup" initdb
    ok "Cluster initialised"
else
    warn "Cluster already exists at ${PGDATA} — skipping initdb"
fi

# ── 4. Tune postgresql.conf ───────────────────────────────────────────────────
info "Writing production tuning to postgresql.conf..."
TOTAL_RAM_MB=$(awk '/MemTotal/ {printf "%d", $2/1024}' /proc/meminfo)
SHARED_BUFFERS_MB=$(( TOTAL_RAM_MB / 4 ))
EFFECTIVE_CACHE_MB=$(( TOTAL_RAM_MB * 3 / 4 ))
WORK_MEM_MB=16
MAINT_WORK_MEM_MB=$(( TOTAL_RAM_MB / 16 ))

# Clamp to sane minimums
(( SHARED_BUFFERS_MB < 128 )) && SHARED_BUFFERS_MB=128
(( MAINT_WORK_MEM_MB < 64 ))  && MAINT_WORK_MEM_MB=64

CONF_INCLUDE="${PGDATA}/postgresql.lms.conf"
cat > "$CONF_INCLUDE" <<EOF
# ── Enable-LMS Production Tuning (auto-generated by pg18-rocky8-setup.sh) ──
listen_addresses = '*'
port = 5432
max_connections = 200

# Memory (auto-calculated from ${TOTAL_RAM_MB} MB RAM)
shared_buffers       = ${SHARED_BUFFERS_MB}MB
effective_cache_size = ${EFFECTIVE_CACHE_MB}MB
work_mem             = ${WORK_MEM_MB}MB
maintenance_work_mem = ${MAINT_WORK_MEM_MB}MB

# Checkpoints
checkpoint_completion_target = 0.9
wal_buffers                  = 16MB

# Query planner
random_page_cost = 1.1
effective_io_concurrency = 200

# Logging
log_destination             = 'stderr'
logging_collector           = on
log_directory               = 'log'
log_filename                = 'postgresql-%a.log'
log_rotation_age            = 1d
log_rotation_size           = 0
log_min_duration_statement  = 1000
log_line_prefix             = '%t [%p]: [%l-1] user=%u,db=%d,app=%a,client=%h '
log_checkpoints             = on
log_connections             = on
log_disconnections          = on
log_lock_waits              = on

# Autovacuum
autovacuum                     = on
autovacuum_max_workers         = 3
autovacuum_naptime             = 1min
autovacuum_vacuum_scale_factor = 0.02
autovacuum_analyze_scale_factor = 0.01

# SSL — disabled for internal LAN (enable if exposing over WAN)
ssl = off
EOF

# Include our tuning file from the main config
if ! grep -q "postgresql.lms.conf" "${PGDATA}/postgresql.conf"; then
    echo "" >> "${PGDATA}/postgresql.conf"
    echo "# Enable-LMS tuning:" >> "${PGDATA}/postgresql.conf"
    echo "include = 'postgresql.lms.conf'" >> "${PGDATA}/postgresql.conf"
fi
ok "postgresql.conf tuned (shared_buffers=${SHARED_BUFFERS_MB}MB)"

# ── 5. Configure pg_hba.conf ─────────────────────────────────────────────────
info "Configuring pg_hba.conf for app server access (${APP_SERVER_IP})..."
HBA="${PGDATA}/pg_hba.conf"

# Remove any existing Enable-LMS block before re-adding
grep -v "^# Enable-LMS" "$HBA" | grep -v "${APP_SERVER_IP}" > "${HBA}.tmp" && mv "${HBA}.tmp" "$HBA"

cat >> "$HBA" <<EOF

# Enable-LMS: allow app server connections (added by pg18-rocky8-setup.sh)
host    ${DB_NAME}    ${DB_USER}    ${APP_SERVER_IP}/32    scram-sha-256
# Allow connections from Docker subnet (172.16.0.0/12 covers default bridge networks)
host    ${DB_NAME}    ${DB_USER}    172.16.0.0/12          scram-sha-256
# Localhost - for pg_dump restore on this machine
local   all           all                                   peer
host    all           all           127.0.0.1/32            scram-sha-256
EOF

ok "pg_hba.conf updated"

# ── 6. Start and enable the service ──────────────────────────────────────────
info "Starting and enabling ${PG_SVC}..."
systemctl enable --now "$PG_SVC"
ok "${PG_SVC} is running"

# ── 7. Create database role and database ─────────────────────────────────────
info "Creating database role '${DB_USER}' and database '${DB_NAME}'..."
sudo -u postgres "$PG_BIN/psql" -v ON_ERROR_STOP=1 <<SQL
-- Idempotent: only create if missing
DO \$\$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${DB_USER}') THEN
        CREATE ROLE "${DB_USER}" WITH LOGIN PASSWORD '${DB_PASSWORD}';
        RAISE NOTICE 'Role ${DB_USER} created';
    ELSE
        ALTER ROLE "${DB_USER}" WITH PASSWORD '${DB_PASSWORD}';
        RAISE NOTICE 'Role ${DB_USER} password updated';
    END IF;
END
\$\$;

SELECT 1 FROM pg_database WHERE datname = '${DB_NAME}' \
\gset _exists_
DO \$\$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_database WHERE datname = '${DB_NAME}') THEN
        PERFORM dblink_exec('dbname=postgres', 'CREATE DATABASE "${DB_NAME}" OWNER "${DB_USER}"');
    END IF;
END
\$\$;
SQL

# CREATE DATABASE can't run in DO block — run directly
sudo -u postgres "$PG_BIN/psql" -v ON_ERROR_STOP=1 \
    -c "SELECT 1 FROM pg_database WHERE datname='${DB_NAME}'" | grep -q 1 || \
    sudo -u postgres "$PG_BIN/psql" -c "CREATE DATABASE \"${DB_NAME}\" OWNER \"${DB_USER}\";"

# Grant privileges
sudo -u postgres "$PG_BIN/psql" -d "$DB_NAME" -c "GRANT ALL PRIVILEGES ON DATABASE \"${DB_NAME}\" TO \"${DB_USER}\";"
sudo -u postgres "$PG_BIN/psql" -d "$DB_NAME" -c "GRANT ALL ON SCHEMA public TO \"${DB_USER}\";"

ok "Database '${DB_NAME}' and role '${DB_USER}' are ready"

# ── 8. Reload PostgreSQL to apply pg_hba changes ──────────────────────────────
info "Reloading PostgreSQL configuration..."
systemctl reload "$PG_SVC"

# ── 9. Open firewall ──────────────────────────────────────────────────────────
if command -v firewall-cmd &>/dev/null; then
    info "Opening port 5432 in firewalld..."
    firewall-cmd --permanent --add-port=5432/tcp
    firewall-cmd --reload
    ok "Port 5432 opened in firewalld"
else
    warn "firewall-cmd not found — ensure port 5432 is open manually"
fi

# ── Summary ───────────────────────────────────────────────────────────────────
echo ""
echo "============================================================"
ok "PostgreSQL ${PG_MAJOR} setup complete on Rocky Linux 8"
echo "  DB Host:     $(hostname -I | awk '{print $1}')"
echo "  DB Port:     5432"
echo "  DB Name:     ${DB_NAME}"
echo "  DB User:     ${DB_USER}"
echo "  Data Dir:    ${PGDATA}"
echo ""
echo "Next step: run db-migrate.sh from the SOURCE machine"
echo "============================================================"
