# Generated by Django 5.2 on 2026-03-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system_config", "0005_add_founder_news_sections"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reporttemplate",
            name="filters_json",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Filter conditions for the report — like Excel column filters",
                verbose_name="Report Filters",
            ),
        ),
        migrations.AlterField(
            model_name="reporttemplate",
            name="schedule_cron",
            field=models.CharField(
                blank=True,
                help_text="How often this report should be auto-generated",
                max_length=100,
                null=True,
                verbose_name="Recurring Schedule",
            ),
        ),
    ]
