# Generated by Django 5.2 on 2026-03-30 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_config', '0006_alter_reporttemplate_filters_json_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classlinkconfig',
            options={'verbose_name': 'Streaming Platform', 'verbose_name_plural': 'Streaming Platforms'},
        ),
        migrations.AlterField(
            model_name='classlinkconfig',
            name='api_endpoint',
            field=models.URLField(blank=True, help_text='The API URL for this platform. YouTube: https://www.googleapis.com/youtube/v3 | Zoom: https://api.zoom.us/v2 | Leave blank to use the default for each platform.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='classlinkconfig',
            name='api_key_reference',
            field=models.CharField(blank=True, help_text='The name of the System Setting that stores your API key. Example: "YOUTUBE_API_KEY" or "ZOOM_API_KEY". The actual key is stored securely in System Settings.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='classlinkconfig',
            name='auto_admit_participants',
            field=models.BooleanField(default=True, help_text='When ON, students join the class directly without waiting in a lobby. When OFF, the teacher must approve each student. Recommended ON for large classes, OFF for small private sessions.'),
        ),
        migrations.AlterField(
            model_name='classlinkconfig',
            name='auto_generate_link',
            field=models.BooleanField(default=False, help_text='When ON, the system automatically creates a meeting/stream link before each class. When OFF, teachers must paste links manually.'),
        ),
        migrations.AlterField(
            model_name='classlinkconfig',
            name='auto_record',
            field=models.BooleanField(default=False, help_text='When ON, live classes are automatically recorded. Recordings are saved to the YouTube channel or cloud storage. Students can watch them later.'),
        ),
        migrations.AlterField(
            model_name='classlinkconfig',
            name='client_id',
            field=models.CharField(blank=True, help_text='OAuth Client ID for this platform. For YouTube/Meet: from Google Cloud Console. For Zoom: from Zoom App Marketplace.', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='classlinkconfig',
            name='client_secret_reference',
            field=models.CharField(blank=True, help_text='The name of the System Setting that stores the client secret. Example: "YOUTUBE_CLIENT_SECRET". The secret itself is stored securely.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='classlinkconfig',
            name='default_duration_minutes',
            field=models.IntegerField(default=60, help_text='Default class length in minutes. Used when creating meetings. Teachers can override this for individual classes. Common values: 45, 60, 90.'),
        ),
        migrations.AlterField(
            model_name='classlinkconfig',
            name='generate_minutes_before',
            field=models.IntegerField(default=15, help_text='How many minutes before the class starts should the link be created? Recommended: 15 minutes. This gives time for the link to be shared with students.'),
        ),
        migrations.AlterField(
            model_name='classlinkconfig',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Turn ON to enable this platform for live classes. Only active platforms can be used to create new class links.'),
        ),
        migrations.AlterField(
            model_name='classlinkconfig',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Set as the default platform. When a teacher creates a new class, this platform will be pre-selected. Only one platform can be default.'),
        ),
        migrations.AlterField(
            model_name='classlinkconfig',
            name='oauth_token_reference',
            field=models.CharField(blank=True, help_text='The name of the System Setting that stores the OAuth token. Example: "YOUTUBE_OAUTH_TOKEN". Usually auto-generated during authorization.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='classlinkconfig',
            name='platform',
            field=models.CharField(choices=[('YOUTUBE', 'YouTube Live'), ('ZOOM', 'Zoom'), ('GOOGLE_MEET', 'Google Meet'), ('MS_TEAMS', 'Microsoft Teams'), ('CUSTOM', 'Custom URL')], help_text='Choose the video platform for live classes. YouTube Live is recommended for large audiences. Zoom/Meet is better for interactive small sessions.', max_length=15),
        ),
        migrations.AlterField(
            model_name='classlinkconfig',
            name='webhook_url',
            field=models.URLField(blank=True, help_text='URL to receive real-time notifications (e.g. when a live stream starts/ends). Leave blank if not needed.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='integrationconfig',
            name='api_endpoint',
            field=models.URLField(blank=True, help_text='The API URL for this service. For YouTube, use: https://www.googleapis.com/youtube/v3  Leave blank to use the default.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='integrationconfig',
            name='api_key',
            field=models.TextField(blank=True, help_text='Your API key from the provider (stored encrypted). For YouTube: get this from Google Cloud Console → APIs & Services → Credentials.', null=True),
        ),
        migrations.AlterField(
            model_name='integrationconfig',
            name='api_secret',
            field=models.TextField(blank=True, help_text='Your API secret key (stored encrypted). Required for some providers. For YouTube, this is usually not needed if you use OAuth.', null=True),
        ),
        migrations.AlterField(
            model_name='integrationconfig',
            name='auto_sync_videos',
            field=models.BooleanField(default=False, help_text='When enabled, the system will automatically import new videos from your YouTube channel. Useful for keeping class recordings in sync.'),
        ),
        migrations.AlterField(
            model_name='integrationconfig',
            name='channel_id',
            field=models.CharField(blank=True, help_text='Your YouTube Channel ID. Find it at: YouTube Studio → Settings → Channel → Advanced Settings. Looks like: UCxxxxxxxxxxxxxxxxxxxxxxxx', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='integrationconfig',
            name='channel_name',
            field=models.CharField(blank=True, help_text='Your YouTube channel\'s display name (e.g. "ABC Academy Live Classes"). This is shown to students so they know which channel to watch.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='integrationconfig',
            name='daily_budget_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum daily spending limit (in your currency). Leave blank for YouTube (free tier). Used mainly for paid APIs.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='integrationconfig',
            name='description',
            field=models.TextField(blank=True, help_text='Optional notes about this integration — e.g. "Used for Class 11 & 12 Physics live streams".', null=True),
        ),
        migrations.AlterField(
            model_name='integrationconfig',
            name='max_requests_per_hour',
            field=models.IntegerField(default=100, help_text="Maximum API calls per hour. YouTube's free quota is ~10,000 units/day. Keep this at 100 or lower to avoid hitting limits. Increase only if you have a paid quota."),
        ),
        migrations.AlterField(
            model_name='integrationconfig',
            name='max_requests_per_user',
            field=models.IntegerField(default=20, help_text='Maximum API calls per user per hour. Prevents a single user from consuming too much of the shared quota. Default: 20.'),
        ),
        migrations.AlterField(
            model_name='integrationconfig',
            name='monthly_budget_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum monthly spending limit. Leave blank for YouTube. Useful for paid services like AI/LLM integrations.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='integrationconfig',
            name='name',
            field=models.CharField(help_text='A friendly name for this integration. For YouTube, use something like "Main YouTube Channel" or "Physics Department YouTube".', max_length=200),
        ),
        migrations.AlterField(
            model_name='integrationconfig',
            name='oauth_client_id',
            field=models.CharField(blank=True, help_text='OAuth Client ID from Google Cloud Console. Found under APIs & Services → Credentials → OAuth 2.0 Client IDs. Looks like: 123456789-abcdef.apps.googleusercontent.com', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='integrationconfig',
            name='oauth_client_secret',
            field=models.TextField(blank=True, help_text='OAuth Client Secret from Google Cloud Console (stored encrypted). Found next to the Client ID in your Google Cloud credentials page.', null=True),
        ),
        migrations.AlterField(
            model_name='integrationconfig',
            name='oauth_refresh_token',
            field=models.TextField(blank=True, help_text='OAuth refresh token (auto-generated). Used to renew the access token when it expires. Do not edit manually.', null=True),
        ),
        migrations.AlterField(
            model_name='integrationconfig',
            name='oauth_token',
            field=models.TextField(blank=True, help_text='OAuth access token (auto-generated during authorization). This is filled automatically when you connect your YouTube account. Do not edit manually unless instructed by support.', null=True),
        ),
        migrations.AlterField(
            model_name='integrationconfig',
            name='oauth_token_expiry',
            field=models.DateTimeField(blank=True, help_text='When the current OAuth token expires. The system refreshes tokens automatically.', null=True),
        ),
        migrations.AlterField(
            model_name='integrationconfig',
            name='playlist_ids',
            field=models.JSONField(blank=True, default=list, help_text='YouTube playlist IDs for organizing recordings. Each playlist groups related videos (e.g. one per subject). Find IDs in YouTube Studio → Content → Playlists. Looks like: PLxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'),
        ),
        migrations.AlterField(
            model_name='integrationconfig',
            name='provider',
            field=models.CharField(help_text='The service provider name. For YouTube integrations, enter "youtube". Other examples: "zoom", "google", "openai".', max_length=100),
        ),
        migrations.AlterField(
            model_name='integrationconfig',
            name='webhook_url',
            field=models.URLField(blank=True, help_text='URL to receive automatic notifications from the provider. For YouTube, this can receive live stream status updates. Leave blank if not using webhooks.', max_length=500, null=True),
        ),
    ]
