# Generated by Django 5.2 on 2026-04-04 21:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_config', '0007_alter_classlinkconfig_options_and_more'),
        ('tenants', '0002_row_level_security'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsTicker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.CharField(help_text='Ticker message text', max_length=500)),
                ('ticker_type', models.CharField(choices=[('INFO', 'Information'), ('ALERT', 'Alert'), ('WARNING', 'Warning'), ('SUCCESS', 'Success'), ('ANNOUNCEMENT', 'Announcement')], default='INFO', max_length=20)),
                ('icon', models.CharField(blank=True, help_text='FontAwesome icon class', max_length=50, null=True)),
                ('link_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('link_text', models.CharField(blank=True, default='Learn More', max_length=100)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority shows first')),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_tickers', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'News Ticker',
                'verbose_name_plural': 'News Tickers',
                'db_table': 'news_tickers',
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
