# Generated by Django 5.2 on 2026-04-04 21:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_config', '0008_newsticker'),
        ('tenants', '0002_row_level_security'),
    ]

    operations = [
        migrations.CreateModel(
            name='TickerItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(help_text='e.g. "Students Enrolled"', max_length=100)),
                ('value', models.CharField(help_text='e.g. "15,000+"', max_length=50)),
                ('icon_class', models.CharField(default='fas fa-star', help_text='FontAwesome class e.g. "fas fa-user-graduate"', max_length=80)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, help_text='NULL = global ticker item', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticker_items', to='tenants.tenant')),
            ],
            options={
                'db_table': 'ticker_items',
                'ordering': ['sort_order'],
            },
        ),
        migrations.DeleteModel(
            name='NewsTicker',
        ),
    ]
