# Generated by Django 5.2 on 2026-04-05 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_config', '0009_add_ticker_item_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='websitesetting',
            options={'ordering': ['section', 'sort_order'], 'verbose_name': 'Website Configuration', 'verbose_name_plural': 'Website Configurations'},
        ),
    ]
